# Change these first
owner: beam7894123 # Your GitHub organization or username, where this repository lives
repo: web_status # The name of this repository


sites:
  - name: Main
    url: https://bezathecat.com/
    
  - name: Thai Translate site
    url: https://thaitranslateby.bezathecat.com/
    
  - name: Archive Server (Hydrus network api)
    url: $MAOW_VERY_SECRET_SITE_1
    __dangerous__disable_verify_peer: true
    expectedStatusCodes:
      - 200



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /web_status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Catty Server
  introTitle: "Beza web server status page ⓛ ̫ ⓛ"
  introMessage: This status page monitors my web server and maybe more!.
  navbar:
    - title: Status
      href: /web_status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  #CSS go here!
  css: ":root{--body-background-color:#000;--body-text-color:#00e7ff --card-background-color: #000 --card-border-color: #00f3ff --nav-background-color: #000 --nav-border-bottom-color #00f3ff --nav-current-border-bottom-color: #00f3ff --up-border-left-color: #20ff00 --degraded-border-left-color: #ffef00 --down-border-left-color: #f00 --change-background-color: #000 --degraded-border-left-color: #000}"
  
i18n:
  footer: This page is [open source]($REPO), 🔌 Powered by [Upptime](https://upptime.js.org), Redesign with 💙 by [BezaTheCat](https://bezathecat.com/) ᗜ ̫ ᗜ

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
